import { Inter, Lora } from "next/font/google";
import "./globals.css";

import type { Metadata } from "next";
import Nav from "./components/Nav";
import ThemeContext from "./contexts/ThemeContext";

export const metadata: Metadata = {
  title: {
    default: "Ovan Zaimul",
    template: "Ovan | %s",
  },
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inter",
});
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-lora",
});

export default async function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${lora.variable} `}
      suppressHydrationWarning
    >
      <head>
        <script
          id="theme-script"
          dangerouslySetInnerHTML={{
            __html: `
          (function() {
            const theme = localStorage.getItem('theme');
            if(theme == "dark"){
              document.documentElement.classList.add("dark")
              }
              })();
              `,
          }}
        />
      </head>
      <body className="bg-cream text-black dark:bg-green dark:text-gold">
        <ThemeContext>
          <header>
            <Nav />
          </header>
          <main className="max-w-4xl mx-auto mt-6">{children}</main>
        </ThemeContext>
      </body>
    </html>
  );
}
