import { Inter, Lora } from "next/font/google";
import "./globals.css";

import type { Metadata } from "next";
import Nav from "./components/Nav";
import ThemeContext, { Theme } from "./contexts/ThemeContext";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "OZ Blog",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-inter",
});
const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-lora",
});

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const cookie = await cookies();
  const theme = cookie.get("theme")?.value || "dark";

  return (
    <html lang="en" className={`${inter.variable} ${lora.variable} ${theme}`}>
      <body className="bg-blue-400 dark:bg-blue-950 dark:text-white">
        <ThemeContext>
          <Nav currentTheme={theme as Theme} />
          {children}
        </ThemeContext>
      </body>
    </html>
  );
}
